---
title: "2_Business.Data.Cleaning"
author: "Brandon Stanaway"
date: "2024-03-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(tidycensus)
require(lubridate)
require(stringr)
require(janitor)
require(sf)
require(mapcdatakeys)
require(dplyr)
require(readxl)

#Load in data keys to add geographies to data later on.
keys <- mapcdatakeys::all_muni_data_keys |> 
  select(
    c(
      muni_name,
      muni_id,
      mapc,
      subrg_acr
    )
  ) |> 
  mutate(
    muni_name = stringr::str_to_title(muni_name)
  )

#Global options to remove scientific notation.
options(scipen = 999)
set.seed(351)

#Set root variables for local data ingestion
da_root <- "C:/Project_Work/Local_Data/Arts_Culture/Industrial_Land_Use/Data/Tabular/raw/"

```

1.0 Load DataAxle and A/C collected data
```{r}
#Load the 2023 DataAxls data
data.axle <- read.csv(
  paste0(da_root, "April_2023 - Massachusetts_New.csv")
)

#Load the 2023 RPA-input revised DataAxle data.
data.axle_revised <- read.csv(
  paste0(da_root, "Revised_DA_23/dataaxle_2023_revised.csv")
)

#Loads the Arts and Culture Spaces recorded in this airtable: https://airtable.com/appY1urvcJd9UmNyr
a.c_spaces <- read.csv(
  paste0(da_root, "AC Sites Airtable.csv")
)

#Loads Arts and Culture Spaces collected as part of the "Making Space for Art" project.
#A link to the airtable is here: https://airtable.com/appScRBzSMyNr011m/shrSi3WTESf2ARtK9/tblUIhUmEgbh8LY1h/viwMZVLjibMWEsHIl?blocks=show
makingspace_spaces <- read.csv(
  paste0(da_root, "MakingSpace AC Sites.csv")
)
```

2.1 Selecting Relevant Variables from DataAxle Data
```{r}
# 2023 edit - changing field names to reflect data axle fields
data.axle_clean <- data.axle |> 
  #Create an OBJECT_ID variable
  mutate(
    OBJECT_ID = seq.int(nrow(data.axle))
  ) |> 
  #Select the variables needed for this analysis.
  dplyr::select(OBJECT_ID, CONAME, STADDR, STCITY, STATE, ZIP, STCODE, 
                CNTYCD, CENSUS, BLKGRP, LATITUDE, LONGITUDE, NAICS, NAICSD, 
                EMPSIZ, LOCEMP, SALVOL, SLSVDT, ZPOPCD, WEALTH, BBUSIN, 
                MBUSIN, SBUSIN, HOME, INDFRM, FEMOWN
  ) |> 
  #Creat variables that represent the 4- and 6-digit versions of NAICS codes
  mutate(
    NAICS.4 = as.character(substr(as.character(NAICS), 1, 4)),
    NAICS.6 = as.character(substr(as.character(NAICS), 1, 6))
  ) |> 
  #Filter for observations with non-N/A employment + are in MA.
  filter(
    !is.na(LOCEMP) & STCODE == 25
  ) 
```


2.2 Harmonizing Town Names
```{r}
#Fix incorrect municipality names in the data
data.axle_clean <- data.axle_clean |> 
  mutate(
    STCITY = case_when(
      
    )
  ) |> 
  #Join MAPC data keys to the data axle data to filter by relevant geographies
  left_join(
    keys,
    c("STCITY" = "muni_name")
  )
```

2.3 Filtering Arts Businesses
```{r}
# From Appendix D (NEFA Core Industries by Creative Category) of 2017 NEFA Report "The Jobs in New England's Creative Economy and Why They Matter"
# Creation of industry groups by six digit NAICS code (assign to establishments with ifelse function)
arch.and.design <- c('541310', '541320', '541340', '541410', '541420', '541430', '541490')
#art.electronic.retail <- c('443142', '448310', '451130', '451140', '451211', '453920', '812921', '812922')
art.retail <- c('448310', '451130', '451140', '451211', '453920', '812921', '812922') # no electronics-related retail
art.arch.manu <- c('332323', '337212', '339910', '339992')
culture.pres <- c('712110', '712120', '712130', '712190')
mach.comm.manu <- c('333244', '334310', '334614')
marketing <- c('541810', '541830', '541840', '541850')
mat.manu <- c('325992', '327110', '327212', '339940')
media <- c('515111', '515112', '515120', '515210', '517110', '519110', '519120', '519130', '532230')
motion.pic.teleprod <- c('512110', '512120', '512131', '512132', '512191', '512199')
music.rec <- c('512210', '512220', '512230', '512240', '512290')
printing <- c('323111', '323113', '323117', '323120')
publishing <- c('511110', '511120', '511130', '511191', '511199')
visual.music.perf.arts <- c('541921', '541922', '611610', '711110', '711120', '711130', '711190', '711510')
wholesale.art.store <- c('423410', '423940', '424110', '424920')

#Create a full list of arts related businesses.
arts_sectors <- c(arch.and.design, art.retail, art.arch.manu, culture.pres,mach.comm.manu,marketing,
                  mat.manu, media, motion.pic.teleprod, music.rec, printing, publishing, visual.music.perf.arts,
                  wholesale.art.store)

#Filter for the arts related businesses.
data.axle_arts.spaces <- data.axle_clean |> 
  filter(
    NAICS.6 %in% arts_sectors
  )
```

2.4 Filter for MAPC geography
```{r}
#Join the MAPC data keys to the arts spaces data.
data.axle_arts.spaces_mapc <- data.axle_arts.spaces |> 
  filter(
    mapc == 1
  )

```

3.0 Compare DataAxle businesses to MAPC-collected Arts data
```{r}
```