---
title: "3_Parcels.Businesses.Spatial.Join"
author: "Brandon Stanaway"
date: "2024-03-28"
output: html_document
---

0.0 Set up
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

require(tidyverse)
require(tidycensus)
require(lubridate)
require(stringr)
require(janitor)
require(sf)
require(mapcdatakeys)
require(dplyr)
require(readxl)
require(ggplot2)
#source("C:/Project_Work/Arts_Culture/Industrial Landuse x Creative Economy/Scripts/municipal_name_fix.func.R")

#Load in data keys to add geographies to data later on.
keys <- mapcdatakeys::all_muni_data_keys |> 
  select(
    c(
      muni_name,
      muni_id,
      mapc,
      subrg_acr
    )
  ) |> 
  mutate(
    muni_name = stringr::str_to_title(muni_name)
  )

#Define land use code to filter on. 
ind_landuse_codes <- c("360","361","362","363","364","365","366","367","368","369",
  "400","401","402","403","404","410","411","412","413","420","421","423","424",
  "425","426","427","428","430","431","432","433","440","441","442","450","451",
  "452","230","231")

#Global options to remove scientific notation.
options(scipen = 999)
set.seed(351)

#Set root variables for local data ingestion
#Parcels shapefile
parcels_root <- "C:/Project_Work/Local_Data/Arts_Culture/Industrial_Land_Use/Data/Spatial/"

#Business data 
biz_root <- "C:/Project_Work/Local_Data/Arts_Culture/Industrial_Land_Use/Data/Tabular/intermediary/"

#Set common projecrions + crs for conversion.
mass_mainland<-"+proj=lcc +lat_1=42.68333333333333 +lat_2=41.71666666666667 +lat_0=41 +lon_0=-71.5 +x_0=200000 +y_0=750000 +ellps=GRS80 +datum=NAD83 +units=m +no_defs"
lat_lon_CRS <- "+proj=longlat +ellps=WGS84 +datum=WGS84 +no_defs"

#Load Land Use Code Crosswalk
LUC_Descriptions <- read.csv(
  "C:/Project_Work/Local_Data/Parcel_DB/comprehensive_adj_use.code_xwalk.csv"
)
```

1.0 Load relevant data
```{r}
#1.1 Parcels
#Load the parcel polygons
mapc_parcels <- st_read(
  paste0(parcels_root, "LPDB.Dec.23_MAPC.Parcels.shp")
)

#1.2 Businesses
#Load the business data
#Convert business point data to a a spatial object (sf object)
mapc_biz.spatial <- readRDS(
  paste0(biz_root, "DA.23_ArtsSpaces.MAPC.cleaned.geocoded.rds")
) |> 
  rowwise() |> 
  mutate(
    lat = tidyr::replace_na(lat, LATITUDE),
    long = tidyr::replace_na(long, LONGITUDE)
  ) |> 
  #Converting the non-spatial data into a spatial object.
  st_as_sf(
    #coords = c("LONGITUDE", "LATITUDE"),
    coords = c("long","lat"),
    crs = st_crs(lat_lon_CRS),
    remove = FALSE
  ) |>
  #Setting CRS to match the polygon's CRS.
  st_transform(
    mass_mainland,
    crs = st_crs(mapc_parcels)
  )
```

2.0 Land Use Code Descriptions + Symbology
```{r}
mapc_parcels <- mapc_parcels |> 
    mutate(
    USE_CODE_SYMB = case_when(
      Min_LUC %in% c("130","131","132") ~ "Residential Vacant",
      Min_LUC %in% c("101") ~ "Single Family Residence",
      Min_LUC %in% c("104","105") ~ "Two or Three Family Residences",
      Min_LUC %in% c("102") ~ "Condominium",
      Min_LUC %in% c("111", "112") ~ "Apartments with Four or more units",
      Min_LUC %in% c("121","122","123","124","125") ~ "Group Quarters",
      Min_LUC %in% c("109","140","107","108","100","110","113","114","115","116","117","118","119","120",
                        "126","127","133","136","137","138","13C","150","160","167","170","171","172","173",
                        "176","180","199","106","103") ~ "Residential Other",
      Min_LUC %in% c("0xx") ~ "Mixed Use",
      Min_LUC %in% c("390","391","392","393") ~ "Commercial Vacant",
      Min_LUC %in% c("300","301","302","303","304","305","306","310","311","312","313","314","315","316",
                        "317","318","321","322","323","324","325","326","330","331","332","333","334","335",
                        "336","337","338","340","342","350","351","352","353","354","355","356","360","361",
                        "362","363","364","365","366","367","368","369","370","371","372","373","374","375",
                        "376","377","380","381","382","383","384","385","386","387","388","389","307","308",
                        "309","319","31l","320","327","328","329","339","33l","343","344","345","346","347",
                        "348","349","34R","378","379","394","395","396","399")~ "Commercial",
      Min_LUC %in% c("440","441","442") ~ "Industrial Vacant",
      Min_LUC %in% c("400","401","402","403","404","410","411","412","413","420","421","422","423","424",
                        "425","426","427","428","430","431","432","433","450","451","452","405","406","407",
                        "408","409","414","415","417","434","435","436","443","444","445","446","465","490",
                        "499") ~ "Industrial",
      Min_LUC %in% c("201","202","210","211","220","221","231","261","271","272","273","274","276","277",
                        "278","279","281","285","290") ~ "Open Space",
      Min_LUC %in% c("601","602","710","711","712","713","714","715","716","717","718","719","720","801",
                        "802","803","804","805","806","807","808","809","810","811","812","813","814","815") ~ "Chapter 61 or 61A or 61B Property",
      Min_LUC %in% c("237","292","600","610","670","700","701","722","730","733","734","736","737","760",
                        "800") ~ "Other Agricultural or Recreational",
      Min_LUC %in% c("930","932","933","936","938","973","974","975","980","982","988","991") ~ "Municipal Vacant",
      Min_LUC %in% c("900","901","910","911","912","913","914","915","916","917","918","919","920","921",
                        "922","923","924","925","926","927","928","929","931","934","935","937","939","981",
                        "985","970","971","972","989","992","993","994") ~ "Federal State or Municipal",
      Min_LUC %in% c("946","950") ~ "Institutional or Exempt Vacant",
      Min_LUC %in% c("940","941","942","943","944","945","945","947","951","952","953","954","955","956",
                        "957","957","958","959","960","961","962","995","996","997","990") ~ "Institutional or Exempt",
      Min_LUC %in% c("902","903","904","905","906","907","908","909","948","949","963","965","966","968",
                        "969","976","977","978","979","983","986","987","998","999") ~ "Tax Exempt Other"
    ),
    USE_CODE_SYMB = replace_na(USE_CODE_SYMB, "Unknown")
  )
```

2.1 Putting the points into the polygons
```{r}
#Testing that the points are projected similar to the polygons.
#Using Stow as an example because it's small + has only a few points
biz_test <- mapc_biz.spatial |> 
  filter(
    STCITY_CLEAN == "Stow"
  )

parcel_test <- mapc_parcels |> 
  filter(
    CITY == "Stow"
  )

ggplot()+
  geom_sf(data = parcel_test)+
  geom_sf(data = biz_test) +
  theme_minimal()

#Hell yeah - the points are in the polygons!
#Lets remove the test dataframes
rm(biz_test, parcel_test)

#Now lets do the point in polygon join for the full dataset
biz_in_parcel <- st_join(mapc_biz.spatial, mapc_parcels, join = st_within)
#parcel_w_biz <- st_join(mapc_parcels, mapc_biz.spatial, join = st_within)
```

2.2 QA/QC SMall Muni Check
```{r}
address_check <- biz_in_parcel |> 
  select(
    Min_LUC,
    CONAME,
    STADDR,
    STCITY_CLEAN,
    LOC_ID,
    ADDR_NUM,
    FULL_STR,
    CITY
  ) |> 
  filter(
    STCITY_CLEAN == "Stow"
  ) |>
  mutate(
    STADDR_NUM = word(STADDR, start = 1, sep = " "),
    addr_num_check = if_else(ADDR_NUM == STADDR_NUM, 1 , 0)
  )

joyleduc_parcel <- mapc_parcels |> 
  filter(
    LOC_ID == "M_201269_909233"
  )

joyleduc_biz <- mapc_biz.spatial |> 
  filter(
    CONAME == "Joy Leduc Photography LLC"
  )

ggplot()+
  geom_sf(data = joyleduc_parcel)+
  geom_sf(data = joyleduc_biz) +
  theme_minimal()

#Multi_address, single loc_id parcels dont have all address information. Make an address match an issue.
#Data Axle does not have full addresses some of the time.
  
```

2.3 Medium Muni Check
```{r}
#Dataset to check address matching
address_check <- biz_in_parcel |> 
  select(
    Min_LUC,
    CONAME,
    STADDR,
    STCITY_CLEAN,
    LOC_ID,
    ADDR_NUM,
    FULL_STR,
    CITY
  ) |> 
  filter(
    STCITY_CLEAN == "Waltham"
  ) |>
  mutate(
    STADDR_NUM = word(STADDR, start = 1, sep = " "),
    addr_num_check = if_else(ADDR_NUM == STADDR_NUM, 1 , 0)
  )

#First Biz
hp_biz <- mapc_biz.spatial |> 
  filter(
    CONAME == "Harvard Printing" & STCITY_CLEAN == "Waltham"
  )

waltham_parcels <- mapc_parcels |> 
  filter(
    CITY == "Waltham" & (FULL_STR == "ELM ST" | FULL_STR == "MOODY ST")
  )

ggplot() +
  geom_sf(data = waltham_parcels, aes(fill = FULL_STR))+
  geom_sf(data = hp_biz) +
  theme_minimal()

#Data axle list this business to be located at 36 Elm Street. The point falls at 362 Moody Street. 
#Data Axle has LAT/LON that do not match the address given in the data.
#FIXED via geocoding!

#Second Biz
rsp_biz <- mapc_biz.spatial |> 
  filter(
    CONAME == "Hajian Architects Inc" & STCITY_CLEAN == "Waltham"
  )

waltham_parcels <- mapc_parcels |> 
  filter(
    CITY == "Waltham" & (FULL_STR == "DEXTER ST" | FULL_STR == "DEXTER AVE")
  )

ggplot() +
  geom_sf(data = waltham_parcels, aes(fill = FULL_STR))+
  geom_sf(data = rsp_biz) +
  theme_minimal()

#Here we have an example of the parcel data not having am address (or parcel) that matches the address of the business (56 Dexter Ave vs 32 Dexter Street). That said, 56 Dexter Ave was geocoded to the appropriate location (no 56 Dexter Ave exists.)
```
2.4 Creating a Parcel-level Count of Businesses and Employment
```{r}
#Table to rejoin to parcel geometries for spatial visualization
Parcel_Biz <- biz_in_parcel |> 
  group_by(
    LOC_ID
  ) |> 
  summarise(
    biz = n(),
    emp = sum(LOCEMP),
    epb = emp/biz
  ) |> 
  ungroup() |> 
  na.omit() |> 
  st_drop_geometry()
```


3.0 Tabular Analysis
3.1 Arts Businesses by Town and NAICS
```{r}
#Set output path for the tables and visualizations associated with this analysis
output_path <- "C:/Project_Work/Arts_Culture/Industrial Landuse x Creative Economy/Data/Outputs/"

#Make a non-sf object copy of the spatialized arts business data to more
#easily facilitate tabular analysis.
data.axle_arts.spaces_mapc <- mapc_biz.spatial |> st_drop_geometry()

#Number of Arts Businesses by Municipality
arts.biz_by.town <- data.axle_arts.spaces_mapc |> 
  group_by(
    STCITY_CLEAN
  ) |> 
  summarise(
    businesses = n(),
    employment = sum(LOCEMP),
    emp.by.biz = round(employment/businesses,2)
  ) |> 
  ungroup() |> 
  arrange(
    desc(businesses)
  )

#Write a csv of the above table
write.csv(
  arts.biz_by.town,
  paste0(output_path, "arts.business_by_muni.csv")
)

#Create a table demonstrating the top 10 municipalities by number of arts businesses
tbl.1 <- arts.biz_by.town |>
  dplyr::slice(1:10) |> 
  gt() |> 
  tab_header(
    title = "NEFA Arts Businesses by Municipality - MAPC"
  ) |> 
  cols_label(
    STCITY_CLEAN = "Municipality",
    businesses = "Businesses",
    employment = "Employment",
    emp.by.biz = "Avg. Employment Per Business"
  ) |> 
  fmt_number(
    columns = c("businesses", "employment"),
    sep_mark = ",",
    decimals = 0
  )

tbl.1 |> 
  gtsave(
    filename = paste0(output_path, "arts.biz_by.town.html")
  )

#Create a bar chart of Top 10 municipalities by number of businsesses
bar_graph.1 <- arts.biz_by.town |> 
  arrange(
    desc(businesses)
  ) |> 
  dplyr::slice(1:10) |> 
  ggplot(aes(x = reorder(STCITY_CLEAN, businesses), y = businesses)) +
  geom_bar(stat = "identity", color = "black", fill = "steelblue") +
  geom_text(aes(label = scales::comma(businesses)), vjust = -0.3, size = 3.5) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Arts Businesses by Municipality (Top 10)",
    x = "Municipality",
    y = "Number of Businesses"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )

#Check it in terminal
bar_graph.1

#Save
ggsave(
  filename = "top10_municipalities_by_arts.businesses.jpeg",
  plot = bar_graph.1,
  device = "jpeg",
  path = output_path
)

#Create a bar chart of Top 10 municipalities by employment
bar_graph.2 <- arts.biz_by.town |> 
  arrange(
    desc(employment)
  ) |> 
  dplyr::slice(1:10) |> 
  ggplot(aes(x = reorder(STCITY_CLEAN, employment), y = employment)) +
  geom_bar(stat = "identity", color = "black", fill = "lavender") +
  geom_text(aes(label = scales::comma(employment)), vjust = -0.3, size = 3.5) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Arts Employment by Municipality (Top 10)",
    x = "Municipality",
    y = "Number of Employees"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )

bar_graph.2

ggsave(
  filename = "top10_municipalities_by_arts.employment.jpeg",
  plot = bar_graph.2,
  device = "jpeg",
  path = output_path
)

#Create a bar chart of Top 10 municipalities by avg. employment per business
bar_graph.3 <- arts.biz_by.town |> 
  arrange(
    desc(emp.by.biz)
  ) |> 
  dplyr::slice(1:10) |> 
  ggplot(aes(x = reorder(STCITY_CLEAN, emp.by.biz), y = emp.by.biz)) +
  geom_bar(stat = "identity", color = "black", fill = "lightgreen") +
  geom_text(aes(label = scales::comma(emp.by.biz)), vjust = -0.3, size = 3.5) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Avg. Arts Employment Per Businesses by Municipality (Top 10)",
    x = "Municipality",
    y = "Avg. Employment Per Businesses"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )

bar_graph.3

ggsave(
  filename = "top10_municipalities_by_arts.employmentbybusiness.jpeg",
  plot = bar_graph.3,
  device = "jpeg",
  path = output_path
)

#Analysis
#99 of MAPC's 101 municipalities are home to at least one arts business.

#=======================================================================================
#Number of Arts Businesses by 6-Digit NAICS Code
arts.biz_by.naics <- data.axle_arts.spaces_mapc |> 
  group_by(
    NAICSD,
    NAICS.6
  ) |> 
  summarise(
    businesses = n(),
    employment = sum(LOCEMP),
    emp.by.biz = round(employment/businesses,2)
  ) |> 
  ungroup() |> 
  arrange(
    desc(businesses)
  )

#Write a csv of the above table
write.csv(
  arts.biz_by.naics,
  paste0(output_path, "arts.business_by_NAICS.csv")
)

#Create a table demonstrating the top 10 NAICS Codes by number of arts businesses
tbl.2 <- arts.biz_by.naics |>
  dplyr::slice(1:10) |> 
  gt() |> 
  tab_header(
    title = "NEFA Art Businesses by NAICS Code - MAPC"
  ) |> 
  cols_label(
    NAICSD = "NAICS",
    NAICS.6 = "6-Digit NAICS Code",
    businesses = "Businesses",
    employment = "Employment",
    emp.by.biz = "Avg. Employment Per Business"
  ) |> 
  fmt_number(
    columns = c("businesses", "employment"),
    sep_mark = ",",
    decimals = 0
  )

tbl.2 |> 
  gtsave(
    filename = paste0(output_path, "arts.biz_by.naics.html")
  )

#Create a bar chart of Top 10 municipalities by number of businsesses
bar_graph.1 <- arts.biz_by.naics |> 
  arrange(
    desc(businesses)
  ) |> 
  dplyr::slice(1:10) |> 
  ggplot(aes(x = reorder(NAICSD, businesses), y = businesses)) +
  geom_bar(stat = "identity", color = "black", fill = "steelblue") +
  geom_text(aes(label = scales::comma(businesses)), vjust = -0.3, size = 3.5) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Arts Businesses by NAICS (Top 10)",
    x = "NAICS Description",
    y = "Number of Businesses"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(color = "black", angle = 90, vjust = 0.5, hjust = 1),
    axis.text.y = element_text(color = "black")
  )

#Check it in terminal
bar_graph.1

#Save
ggsave(
  filename = "top10_naics_by_arts.businesses.jpeg",
  plot = bar_graph.1,
  device = "jpeg",
  path = output_path
)

#Create a bar chart of Top 10 municipalities by employment
bar_graph.2 <- arts.biz_by.naics |> 
  arrange(
    desc(employment)
  ) |> 
  dplyr::slice(1:10) |> 
  ggplot(aes(x = reorder(NAICSD, employment), y = employment)) +
  geom_bar(stat = "identity", color = "black", fill = "lavender") +
  geom_text(aes(label = scales::comma(employment)), vjust = -0.3, size = 3.5) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Arts Employment by NAICS (Top 10)",
    x = "NAICS Description",
    y = "Number of Employees"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )

bar_graph.2

ggsave(
  filename = "top10_naics_by_arts.employment.jpeg",
  plot = bar_graph.2,
  device = "jpeg",
  path = output_path
)

#Create a bar chart of Top 10 municipalities by avg. employment per business
bar_graph.3 <- arts.biz_by.naics |> 
  arrange(
    desc(emp.by.biz)
  ) |> 
  dplyr::slice(1:10) |> 
  ggplot(aes(x = reorder(NAICSD, emp.by.biz), y = emp.by.biz)) +
  geom_bar(stat = "identity", color = "black", fill = "lightgreen") +
  geom_text(aes(label = scales::comma(emp.by.biz)), vjust = -0.3, size = 3.5) +
  scale_x_discrete(limits = rev) +
  scale_y_continuous(label = scales::comma) +
  labs(
    title = "Avg. Arts Employment Per Businesses by Municipality (Top 10)",
    x = "NAICS Description",
    y = "Avg. Employment Per Businesses"
  ) +
  theme_minimal() +
  theme(
    axis.text.x = element_text(color = "black"),
    axis.text.y = element_text(color = "black")
  )

bar_graph.3

ggsave(
  filename = "top10_NAICS_by_arts.employmentbybusiness.jpeg",
  plot = bar_graph.3,
  device = "jpeg",
  path = output_path
)

#Analysis
#49 different types of arts business are represented in the MAPC region.


#==============================================================================
#Number of Arts businesses by municipality and 6-Digit NAICS Code
arts.biz_by.town.by.naics <- data.axle_arts.spaces_mapc |> 
  group_by(
    STCITY_CLEAN,
    NAICSD,
    NAICS.6
  ) |> 
  summarise(
    businesses = n(),
    employment = sum(LOCEMP),
    emp.by.biz = round(employment/businesses,2)
  ) |> 
  ungroup() |> 
  arrange(
    desc(desc(STCITY_CLEAN))
  )

#Write a csv of the above table
write.csv(
  arts.biz_by.town.by.naics,
  paste0(output_path, "arts.business_by_muni_by_NAICS.csv")
)

#Analysis
#
```

3.2 Arts Businesses by Land Use Codes
```{r}
output_path <- "C:/Project_Work/Arts_Culture/Industrial Landuse x Creative Economy/Data/Outputs/"

#Density plot of employment of arts businesses in parcel
print(summary(biz_in_parcel |> select()))

biz_in_parcel |> 
  ggplot(aes(x = LOCEMP)) +
  geom_density() + 
  theme_minimal()

#Business by Minimum land use codes
Biz_by_LUC <- biz_in_parcel |> 
  group_by(
    USE_CODE_SYMB,
  ) |> 
  summarise(
    Num_Business = n(),
    Employment = sum(LOCEMP),
    Avg_emp = round(Employment/Num_Business, 2)
  ) |> 
  ungroup() |> 
  na.omit() |> 
  st_drop_geometry() |> 
  arrange(
    desc(Num_Business)
  )

write.csv(
  Biz_by_LUC,
  paste0(output_path, "businesses_by_LUC.type.csv")
)

#Businesses by land use codes and 6-Digit NAICS
Biz_by_LUC_by_NAICS <- biz_in_parcel |> 
  group_by(
    USE_CODE_SYMB,
    NAICSD,
    NAICS.6
  ) |> 
  summarise(
    Num_Business = n(),
    Employment = sum(LOCEMP),
    Avg_emp = round(Employment/Num_Business, 2)
  ) |> 
  ungroup() |> 
  na.omit() |> 
  st_drop_geometry() |> 
  arrange(
    desc(Num_Business)
  )

write.csv(
  Biz_by_LUC_by_NAICS,
  paste0(output_path, "businesses_by_LUC.type_by_NAICS.csv")
)

#Businesses by Land Use Code and Municipality
Biz_by_LUC_Muni <- biz_in_parcel |> 
  group_by(
    USE_CODE_SYMB,
    muni_name
  ) |> 
  summarise(
    Num_Business = n(),
    Employment = sum(LOCEMP),
    Avg_emp = round(Employment/Num_Business, 2)
  ) |> 
  ungroup() |> 
  na.omit() |> 
  st_drop_geometry() |> 
  arrange(
    desc(Num_Business)
  )

write.csv(
 Biz_by_LUC_Muni,
  paste0(output_path, "businesses_by_LUC.type_by_Muni.csv")
)

```

4.0 Spatial Analysis
```{r}
#Lets visualize the parcels that do have arts businesses in them
waltham_parcels_full <- mapc_parcels |> 
  filter(
    CITY == "Somerville"
  ) |> 
  left_join(
    Parcel_Biz,
    by = c("LOC_ID")
  ) |> 
  mutate(
    biz = tidyr::replace_na(biz, 0),
    emp = tidyr::replace_na(emp, 0)
  )

#
ggplot() +
  geom_sf(data = waltham_parcels_full, aes(fill = biz), linewidth = 0) +
  theme_minimal()

#
waltham_parcels_ind <- waltham_parcels_full |> 
  filter(
    USE_CODE_SYMB == "Industrial" | USE_CODE_SYMB == "Industrial Vacant"
  )

ggplot() +
  geom_sf(data = waltham_parcels_full, aes(fill = biz), color = NA) +
  geom_sf(data = waltham_parcels_ind, aes(color = USE_CODE_SYMB), fill = NA) +
  theme_minimal()

```